# Generated by Django 2.2.10 on 2020-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(related_name='cart_item', to='orders.CartItem'),
        ),
    ]
