# Generated by Django 2.2.10 on 2020-04-02 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cartitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
