# Generated by Django 2.2.10 on 2020-04-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200402_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(default='Paid', max_length=64),
        ),
    ]
