# Generated by Django 2.2.10 on 2020-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200405_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='complete_date',
            field=models.DateTimeField(null=True),
        ),
    ]
